function wayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLinewayTooLongLine()
  if true then end
end
